apiVersion: v1
kind: ServiceAccount
metadata:
  name: tilloo-admin
  namespace: tilloo-services
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tilloo-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tilloo-admin
  namespace: tilloo-services
---
apiVersion: v1
kind: Service
metadata:
  name: disquetron-service
  namespace: tilloo-services
spec:
  ports:
  - port: 7711
    targetPort: 7711
  selector:
    app: disquetron
    namespace: tilloo-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: disquetron-deployment
  namespace: tilloo-services
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      app: disquetron
      namespace: tilloo-services
  template:
    metadata:
      labels:
        app: disquetron
        namespace: tilloo-services
    spec:
      containers:
      - name: disquetron
        image: jobflow/disque
        ports:
        - containerPort: 7711
      nodeSelector:
        beta.kubernetes.io/arch: amd64
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: tilloo-services
spec:
  # type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: scheduler
    namespace: tilloo-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  namespace: tilloo-services
spec:  
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      app: scheduler
      namespace: tilloo-services
  template:
    metadata:
      labels:
        app: scheduler
        namespace: tilloo-services
    spec:
      serviceAccountName: tilloo-admin
      containers:
      - name: scheduler
        image: chriskinsman/rpi-tilloo:latest
        env:
        - name: DEBUG
          value: tilloo:*
        command: ['/tilloo/bin/scheduler.js']
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/arch: arm
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: tilloo-services
spec:
  # type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web
    namespace: tilloo-services
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: tilloo-services
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      app: web
      namespace: tilloo-services
  template:
    metadata:
      labels:
        app: web
        namespace: tilloo-services
    spec:
      serviceAccountName: tilloo-admin
      containers:
      - name: web
        image: chriskinsman/rpi-tilloo:latest
        env:
        - name: DEBUG
          value: tilloo:*
        command: ['/tilloo/app/app.js']
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/arch: arm
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logger
  namespace: tilloo-services
spec:
  selector:
    matchLabels:
      app: logger
      namespace: tilloo-services
  template:
    metadata:
      labels:
        app: logger
        namespace: tilloo-services
    spec:      
      serviceAccountName: tilloo-admin
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: logger
        image: chriskinsman/rpi-tilloo:latest
        env:
        - name: DEBUG
          value: tilloo:*
        command: ['/tilloo/bin/k8slogger.js']
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlib
          mountPath: /var/lib/docker/containers
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
          type: Directory
      - name: varlib
        hostPath:
          path: /var/lib/docker/containers
          type: Directory
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tilloo-ingress
  namespace: tilloo-services
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
    nginx.ingress.kubernetes.io/proxy-send-timeout: 3600

spec:
  rules:
    - host: tilloo.local
      http:
        paths:
          - path: /socket.io/
            backend:
              serviceName: scheduler-service
              servicePort: 80
          - path: /
            backend:
              serviceName: web-service
              servicePort: 80